sudo: required
dist: trusty
language:
  - cpp
  - python

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install cmake -y
  - sudo apt-get install xorg-dev -y
  - sudo apt-get install libgl1-mesa-dev -y

compiler:
  - gcc
  - clang

script:
  - git submodule init
  - git submodule update
  - mkdir build
  - cd build
  - cmake .. -DTRAVIS_CI=TRUE
  - make
  - ./all_tests