sudo: required
dist: trusty
language:
  - cpp
  - python

before_install:
  - echo "yes" | sudo add-apt-repository ppa:kalakris/cmake
  - sudo apt-get update -qq
  - sudo apt-get install cmake -y

compiler:
  - gcc
  - clang

script:
  - git submodule init
  - git submodule update
  - mkdir build
  - cd build
  - cmake .. -DTRAVIS_CI=TRUE
  - make
  - ./all_tests